### ISSUE TITLE
License

### ISSUE THREAD

**Issue by satvik007** [Southclaws/supervillain#9]
There is no license on this repository. It will be great if you can add one.

**Comment by AndrianBdn** [comment]
Dear @Southclaws 

My company has developed Golang to zod converter, which also supports [validator](https://github.com/go-playground/validator) annotations and self referential types. We would love to make it open-source (not sure if you want a PR with validator stuff?). Since it contains some supervillain code, would be good to have an actual license for it.

I you really intend "do whatever you want with it", you should consider the [Zero-Clause BSD license (0BSD)](https://opensource.org/licenses/0BSD). BSD/MIT may also be a good choice.

**Comment by Southclaws** [comment]
Sorry completely forgot about this, added an MIT license to the repo 👍
